# Cloud Build 배포 설정
# Senior MHealth Core Service - 제5강 구현

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/senior-mhealth-core-service:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/senior-mhealth-core-service:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/senior-mhealth-core-service:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/senior-mhealth-core-service:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'senior-mhealth-core-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/senior-mhealth-core-service:$BUILD_ID'
      - '--region'
      - 'asia-northeast1'  # 서울 리전
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/senior-mhealth-core-service:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/senior-mhealth-core-service:latest'

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100